export const NavLinks={
    '/planning':"Dry Process -> Planning",
    '/washreceive':"Wash Receive",
    '/qceditdel':"Dry Process -> QC Update",
    '/whiskerin':"Dry Process -> Whisker In",
    '/whiskerqc':"Dry Process -> Whisker QC",
    '/whiskeroutput':"Dry Process -> Whisker QC Pass",
    '/laserwhiskerin':"Dry Process -> Laser Whisker In",
    '/laserwhiskerqc':"Dry Process -> Laser Whisker QC",
    '/laserwhiskeroutput':"Dry Process -> Laser Whisker QC Pass",
    '/brushin':"Dry Process -> Brush In",
    '/brushqc':"Dry Process -> Brush QC",
    '/brushoutput':"Dry Process -> Brush QC Pass",
    '/laserbrushin':"Dry Process -> Laser Brush In",
    '/laserbrushqc':"Dry Process -> Laser Brush QC",
    '/laserbrushoutput':"Dry Process -> Laser Brush QC Pass",
    '/wrinklein':"Dry Process -> Wrinkle In",
    '/wrinkleqc':"Dry Process -> Wrinkle QC",
    '/wrinkleoutput':"Dry Process -> Wrinkle QC Pass",
    '/tagin':"Dry Process -> Tag In",
    '/tagqc':"Dry Process -> Tag QC",
    '/tagoutput':"Dry Process -> Tag QC Pass",
    '/tiein':"Dry Process -> Tie In",
    '/tieqc':"Dry Process -> Tie QC",
    '/tieoutput':"Dry Process -> Tie QC Pass",
    '/firstwash/dryerconveyorin':"1st Wash -> Dryer -> Dryer Conveyor In",
    '/firstwash/dryerconveyorout':"1st Wash -> Dryer -> Dryer Conveyor Out",
    '/firstwash/dryerovenin':"1st Wash -> Dryer -> Dryer Oven In",
    '/firstwash/dryerovenout':"1st Wash -> Dryer -> Dryer Oven Out",
    '/firstwash/dryertumblein':"1st Wash -> Dryer -> Dryer Tumble In",
    '/firstwash/dryertumbleout':"1st Wash -> Dryer -> Dryer Tumble Out",
    '/firstwash/processfinish':"1st Wash -> Unload -> Process Finish & Unload Start",//"
    '/firstwash/hydroout':"1st Wash -> Hydro -> Hydro Out",
    '/firstwash/unloadfinish':"1st Wash -> Unload -> Unload Finish",
    '/firstwash/loadfinish':"1st Wash -> Load -> Load Finish & Process Start",
    '/firstwash/rewashcreatebatch':"1st Wash -> Rewash -> Create Batch",
    '/firstwash/loadstart':"1st Wash -> Load -> Load Start",
    '/firstwash/createbatch':"1st Wash -> Create Batch",
    '/firstwashqc':"1st Wash -> QC",
    '/firstwash/hydroin':"1st Wash -> Hydro -> Hydro In",
    '/secondwash/createbatch':"2nd Wash -> Create Batch",
    '/secondwash/hydroin':"2nd Wash -> Hydro -> Hydro In",
    '/secondwash/hydroout':"2nd Wash -> Hydro -> Hydro Out",
    '/secondwash/loadstart':"2nd Wash -> Load -> Load Start",
    '/secondwash/loadfinish':"2nd Wash -> Load -> Load Finish & Process Start",
    '/secondwash/unloadfinish':"2nd Wash -> Unload -> Unload Finish",
    '/secondwashqc':"2nd Wash -> QC",
    '/secondwash/rewashcreatebatch':"2nd Wash -> Rewash -> Create Batch",
    '/secondwash/processfinish':"2nd Wash -> Unload -> Process Finish & Unload Start",
    '/secondwash/dryerconveyorin':"2nd Wash -> Dryer -> Dryer Conveyor In",
    '/secondwash/dryerconveyorout':"2nd Wash -> Dryer -> Dryer Conveyor Out",
    '/secondwash/dryerovenin':"2nd Wash -> Dryer -> Dryer Oven In",
    '/secondwash/dryerovenout':"2nd Wash -> Dryer -> Dryer Oven Out",
    '/secondwash/dryertumblein': "2nd Wash -> Dryer -> Dryer Tumble In",
    '/secondwash/dryertumbleout':"2nd Wash -> Dryer -> Dryer Tumble Out",
    '/thirdwash/createbatch':"3rd Wash -> Create Batch",
    '/thirdwash/hydroin':"3rd Wash -> Hydro -> Hydro In",
    '/thirdwash/hydroout':"3rd Wash -> Hydro -> Hydro Out",
    '/thirdwash/loadstart':"3rd Wash -> Load -> Load Start",
    '/thirdwash/loadfinish':"3rd Wash -> Load -> Load Finish & Process Start",
    '/thirdwash/unloadfinish':"3rd Wash -> Unload -> Unload Finish",
    '/thirdwashqc':"3rd Wash -> QC",
    '/thirdwash/rewashcreatebatch':"3rd Wash -> Rewash -> Create Batch",
    '/thirdwash/processfinish':"3rd Wash -> Unload -> Process Finish & Unload Start",
    '/thirdwash/dryerconveyorin':"3rd Wash -> Dryer -> Dryer Conveyor In",
    '/thirdwash/dryerconveyorout':"3rd Wash -> Dryer -> Dryer Conveyor Out",
    '/thirdwash/dryerovenin':"3rd Wash -> Dryer -> Dryer Oven In",
    '/thirdwash/dryerovenout':"3rd Wash -> Dryer -> Dryer Oven Out",
    '/thirdwash/dryertumblein':"3rd Wash -> Dryer -> Dryer Tumble In",
    '/thirdwash/dryertumbleout':"3rd Wash -> Dryer -> Dryer Tumble Out",
    '/finalwash/createbatch':"Final Wash -> Create Batch",
    '/finalwash/hydroin':"Final Wash -> Hydro -> Hydro In",
    '/finalwash/hydroout':"Final Wash -> Hydro -> Hydro Out",
    '/finalwash/loadstart':"Final Wash -> Load -> Load Start",
    '/finalwash/loadfinish':"Final Wash -> Load -> Load Finish & Process Start",
    '/finalwash/unloadfinish':"Final Wash -> Unload -> Unload Finish",
    '/finalwashqc':"Final Wash -> QC",
    '/finalwash/rewashcreatebatch':"Final Wash -> Rewash -> Create Batch",
    '/finalwash/processfinish':"Final Wash -> Unload -> Process Finish & Unload Start",
    '/finalwash/dryerconveyorin':"Final Wash -> Dryer -> Dryer Conveyor In",
    '/finalwash/dryerconveyorout':"Final Wash -> Dryer -> Dryer Conveyor Out",
    '/finalwash/dryerovenin':"Final Wash -> Dryer -> Dryer Oven In",
    '/finalwash/dryerovenout':"Final Wash -> Dryer -> Dryer Oven Out",
    '/finalwash/dryertumblein':"Final Wash -> Dryer -> Dryer Tumble In",
    '/finalwash/dryertumbleout':"Final Wash -> Dryer -> Dryer Tumble Out"
}