import ROLES from "./Roles";

export const wetProcessRoles = [
  // First Wash
  ROLES.FirstHydroIn,
  ROLES.FirstHydroOut,
  ROLES.FirstLoadStart,
  ROLES.FirstLoadFinish,
  ROLES.FirstProcessFinish,
  ROLES.FirstUnloadFinish,
  ROLES.FirstTumbleIn,
  ROLES.FirstTumbleOut,
  ROLES.FirstConveyerIn,
  ROLES.FirstConveyerOut,
  ROLES.FirstOvenIn,
  ROLES.FirstOvenOut,
  ROLES.FirstWashQC,
  ROLES.FirstWashBatch,
  ROLES.FirstWashRewashBatch,

  // Second Wash
  ROLES.SecondHydroIn,
  ROLES.SecondHydroOut,
  ROLES.SecondLoadStart,
  ROLES.SecondLoadFinish,
  ROLES.SecondProcessFinish,
  ROLES.SecondUnloadFinish,
  ROLES.SecondTumbleIn,
  ROLES.SecondTumbleOut,
  ROLES.SecondConveyerIn,
  ROLES.SecondConveyerOut,
  ROLES.SecondOvenIn,
  ROLES.SecondOvenOut,
  ROLES.SecondWashQC,
  ROLES.SecondWashBatch,
  ROLES.SecondWashRewashBatch,

  // Third Wash
  ROLES.ThirdHydroIn,
  ROLES.ThirdHydroOut,
  ROLES.ThirdLoadStart,
  ROLES.ThirdLoadFinish,
  ROLES.ThirdProcessFinish,
  ROLES.ThirdUnloadFinish,
  ROLES.ThirdTumbleIn,
  ROLES.ThirdTumbleOut,
  ROLES.ThirdConveyerIn,
  ROLES.ThirdConveyerOut,
  ROLES.ThirdOvenIn,
  ROLES.ThirdOvenOut,
  ROLES.ThirdWashQC,
  ROLES.ThirdWashBatch,
  ROLES.ThirdWashRewashBatch,

  // Final Wash
  ROLES.FinalHydroIn,
  ROLES.FinalHydroOut,
  ROLES.FinalLoadStart,
  ROLES.FinalLoadFinish,
  ROLES.FinalProcessFinish,
  ROLES.FinalUnloadFinish,
  ROLES.FinalTumbleIn,
  ROLES.FinalTumbleOut,
  ROLES.FinalConveyerIn,
  ROLES.FinalConveyerOut,
  ROLES.FinalOvenIn,
  ROLES.FinalOvenOut,
  ROLES.FinalWashQC,
  ROLES.FinalWashBatch,
  ROLES.FinalWashRewashBatch,
];